import { useMemo, useState } from 'react'

const decisions=[
 ['Migration','Rehost','Replatform','Choose rehost for speed/compatibility; replatform when managed services reduce operations without major code change.'],
 ['Network','Hub-Spoke','vWAN','Hub-spoke gives direct control; vWAN becomes compelling for large branch/transit estates and managed routing.'],
 ['App Hosting','App Service','AKS','Prefer simpler PaaS when requirements fit; AKS adds control and operational burden.'],
 ['Database','SQL MI','SQL DB','MI improves SQL Server compatibility; SQL DB is more cloud-native with narrower instance-level compatibility.'],
 ['AI','RAG','Fine-tuning','RAG grounds answers in changing enterprise knowledge; fine-tuning primarily changes model behavior/style.'],
 ['Commercial','Fixed Price','T&M','Fixed price needs bounded scope and assumptions; T&M handles uncertainty but shifts budget risk to customer.'],
]
export function ArchitectureLab(){const [open,setOpen]=useState(0);return <section className="panel lab"><p className="eyebrow">ARCHITECTURE DECISION LAB</p><h2>Choose based on trade-offs, not fashion</h2><div className="decision-tabs">{decisions.map((d,i)=><button className={open===i?'selected':''} onClick={()=>setOpen(i)} key={d[0]}>{d[0]}</button>)}</div><div className="decision-box"><div><strong>{decisions[open][1]}</strong><span>Option A</span></div><b>VS</b><div><strong>{decisions[open][2]}</strong><span>Option B</span></div></div><p className="formula">{decisions[open][3]}</p><div className="arch-flow"><span>Business outcome</span><i>→</i><span>Requirements</span><i>→</i><span>Options</span><i>→</i><span>Trade-offs</span><i>→</i><span>Decision</span><i>→</i><span>Evidence</span></div></section>}

export function ConsumptionLab(){const [vm,setVm]=useState(500),[compute,setCompute]=useState(14000),[other,setOther]=useState(35);const monthly=vm*compute*(1+other/100),annual=monthly*12;return <section className="panel lab"><p className="eyebrow">AZURE CONSUMPTION LAB</p><h2>Build a ROM, then validate it properly</h2><div className="input-grid"><label>VM count<input type="number" value={vm} onChange={e=>setVm(+e.target.value)}/></label><label>Illustrative compute ₹/VM/month<input type="number" value={compute} onChange={e=>setCompute(+e.target.value)}/></label><label>Storage/network/ops uplift %<input type="number" value={other} onChange={e=>setOther(+e.target.value)}/></label></div><div className="result-grid"><div><strong>₹{(monthly/100000).toFixed(1)}L</strong><span>Illustrative monthly</span></div><div><strong>₹{(annual/10000000).toFixed(2)}Cr</strong><span>Illustrative annual</span></div><div><strong>ROM</strong><span>Confidence class</span></div></div><p className="warning">Training model only. Validate SKU, region, utilization, licensing, reservation/savings plan, storage, egress, backup, DR, monitoring and support using authoritative Azure pricing inputs.</p></section>}

export function StaffingLab(){const [architects,setArchitects]=useState(2),[engineers,setEngineers]=useState(8),[months,setMonths]=useState(8),[util,setUtil]=useState(80);const pm=useMemo(()=>((architects+engineers)*months*util/100),[architects,engineers,months,util]);return <section className="panel lab"><p className="eyebrow">RESOURCE LOADING LAB</p><h2>Make staffing traceable to workload and timeline</h2><div className="input-grid"><label>Architects<input type="number" value={architects} onChange={e=>setArchitects(+e.target.value)}/></label><label>Engineers<input type="number" value={engineers} onChange={e=>setEngineers(+e.target.value)}/></label><label>Months<input type="number" value={months} onChange={e=>setMonths(+e.target.value)}/></label><label>Utilization %<input type="number" value={util} onChange={e=>setUtil(+e.target.value)}/></label></div><div className="result-grid"><div><strong>{architects+engineers}</strong><span>People</span></div><div><strong>{pm.toFixed(1)}</strong><span>Person-months</span></div><div><strong>{util}%</strong><span>Planned utilization</span></div></div><p className="formula">Defend staffing with WBS, productivity, concurrency, skills, governance and stabilization needs. Headcount alone is not an estimate.</p></section>}

const stakeholders=[['CIO','Business outcome, risk, timeline','Decision value and transformation confidence'],['CISO','Control effectiveness, data exposure, compliance','Threat/control mapping and exceptions'],['Finance','Cost, margin, assumptions','Transparent model and sensitivity'],['Procurement','Price, terms, comparability','Scope boundaries and commercial logic'],['Delivery','Feasibility, staffing, dependencies','WBS, RAID, assumptions and acceptance'],['Microsoft','Azure consumption and strategic alignment','Workload plan, architecture and consumption logic']]
export function StakeholderLab(){return <section className="panel lab"><p className="eyebrow">STAKEHOLDER SIMULATOR</p><h2>Same deal. Different decision lens.</h2><div className="stake-grid">{stakeholders.map(([who,care,evidence])=><article key={who}><strong>{who}</strong><p>{care}</p><span>Bring: {evidence}</span></article>)}</div></section>}
