import {useMemo,useState} from 'react'
type Choice={name:string;security:number;cost:number;effort:number;ops:number;readiness:number;note:string};type Decision={area:string;why:string;choices:Choice[]}
const decisions:Decision[]=[
{area:'Network topology',why:'Controls connectivity scale, routing ownership and operational model.',choices:[{name:'Hub-spoke',security:4,cost:4,effort:3,ops:3,readiness:4,note:'Good control with explicit routing. Fits many estates but shared-service design matters.'},{name:'Azure vWAN',security:4,cost:3,effort:4,ops:4,readiness:5,note:'Useful for larger distributed connectivity patterns. Validate feature and operating-model fit.'}]},
{area:'Hybrid connectivity',why:'Migration throughput and production dependency paths rely on it.',choices:[{name:'Site-to-site VPN',security:3,cost:5,effort:5,ops:4,readiness:3,note:'Fast to establish, but capacity and resiliency may constrain migration or production.'},{name:'ExpressRoute',security:4,cost:3,effort:2,ops:4,readiness:5,note:'Predictable private connectivity. Lead time, provider dependencies and redundancy must be planned.'}]},
{area:'Traffic inspection',why:'Central egress and east-west policy can affect routes and application flows.',choices:[{name:'Azure Firewall',security:5,cost:3,effort:4,ops:4,readiness:4,note:'Azure-native policy and logging. Size and route design still need validation.'},{name:'NVA firewall',security:5,cost:3,effort:3,ops:3,readiness:3,note:'Can align with existing enterprise tooling. Licensing, HA and routing add dependencies.'}]},
{area:'PaaS exposure',why:'Public versus private access changes DNS, routing and operational complexity.',choices:[{name:'Private endpoints',security:5,cost:3,effort:2,ops:3,readiness:3,note:'Strong private-access pattern, but private DNS and network integration become critical.'},{name:'Public endpoint + controls',security:3,cost:5,effort:5,ops:4,readiness:5,note:'Simpler path where policy allows. Validate data and regulatory requirements before selecting.'}]},
{area:'Privileged access',why:'Administrative access is a control-plane risk and audit concern.',choices:[{name:'Entra PIM + RBAC',security:5,cost:4,effort:3,ops:4,readiness:4,note:'Time-bound privileged access with role governance. Requires identity process maturity.'},{name:'Standing admin roles',security:1,cost:5,effort:5,ops:2,readiness:2,note:'Operationally easy but creates material privilege exposure and weak governance.'}]},
{area:'Infrastructure delivery',why:'Repeatability, drift control and handover depend on how the platform is built.',choices:[{name:'Terraform IaC',security:4,cost:4,effort:3,ops:5,readiness:5,note:'Repeatable and reviewable. Requires state, pipeline and module governance.'},{name:'Portal/manual build',security:2,cost:4,effort:4,ops:2,readiness:2,note:'Fast for isolated experiments, weak for repeatable enterprise delivery and drift control.'}]},
{area:'Resilience',why:'RTO/RPO and application architecture determine backup and DR requirements.',choices:[{name:'Backup + regional DR',security:4,cost:2,effort:2,ops:3,readiness:4,note:'Higher resilience with meaningful cost and testing obligations. Must be workload justified.'},{name:'Backup only',security:3,cost:5,effort:4,ops:4,readiness:3,note:'Lower cost, but does not satisfy every workload availability or disaster-recovery requirement.'}]}
]
export function ArchitectureDecisionLab(){const [selected,setSelected]=useState<Record<number,number>>({});const picked=Object.keys(selected).length;const totals=useMemo(()=>{const vals=Object.entries(selected).map(([i,j])=>decisions[+i].choices[j]);if(!vals.length)return{security:0,cost:0,effort:0,ops:0,readiness:0};const avg=(k:keyof Choice)=>Math.round(vals.reduce((s,v)=>s+(typeof v[k]==='number'?v[k] as number:0),0)/vals.length*20);return{security:avg('security'),cost:avg('cost'),effort:avg('effort'),ops:avg('ops'),readiness:avg('readiness')}},[selected]);return <section className="panel lab"><p className="eyebrow">ARCHITECTURE DECISION LAB</p><h2>Every architecture choice creates delivery consequences</h2><p className="lead">Select patterns for the fictional Contoso landing zone. Scores show training trade-offs, not Microsoft product ratings. A real design must be validated against requirements, CAF, Well-Architected guidance, security policy, cost and operations.</p><div className="arch-scores">{Object.entries(totals).map(([k,v])=><div key={k}><strong>{v}%</strong><span>{k==='cost'?'Cost efficiency':k==='effort'?'Delivery ease':k==='ops'?'Operability':k[0].toUpperCase()+k.slice(1)}</span></div>)}</div><div className="arch-decisions">{decisions.map((d,i)=><article key={d.area}><div><small>DECISION {i+1}</small><h3>{d.area}</h3><p>{d.why}</p></div><div className="arch-options">{d.choices.map((c,j)=><button className={selected[i]===j?'selected':''} onClick={()=>setSelected(s=>({...s,[i]:j}))} key={c.name}><strong>{c.name}</strong><span>{c.note}</span>{selected[i]===j&&<small>Security {c.security}/5 · Cost {c.cost}/5 · Delivery {c.effort}/5 · Ops {c.ops}/5 · Readiness {c.readiness}/5</small>}</button>)}</div></article>)}</div><div className="architecture-map"><span>IDENTITY</span><i>↓</i><div><span>ON-PREM</span><b>⇄</b><span>ER / VPN</span><b>⇄</b><span>HUB / vWAN</span><b>→</b><span>WORKLOAD SPOKES</span></div><i>↓</i><div><span>FIREWALL</span><b>·</b><span>PRIVATE DNS</span><b>·</b><span>MONITORING</span><b>·</b><span>BACKUP / DR</span></div><i>↓</i><span>TERRAFORM + PIPELINE GOVERNANCE</span></div><div className="review"><strong>Senior Manager architecture gate</strong><p>{picked}/{decisions.length} decisions recorded. Before baseline approval, tie each material choice to a customer requirement, owner, cost/effort consequence, security control and operational responsibility. An elegant diagram without these links is not a defensible solution.</p></div></section>}
