import {useMemo,useState} from 'react'
type Impact={customer:number;architecture:number;effort:number;schedule:number;margin:number;acr:number;alignment:number;risk:number}
type Choice={label:string;impact:Impact;feedback:string}
type Scenario={title:string;context:string;decision:string;choices:Choice[]}
const scenarios:Scenario[]=[
{title:'The six-month promise',context:'Contoso wants 500 VMware VMs migrated in six months. Dependency evidence is incomplete and only 40% of application owners have validated business criticality.',decision:'What do you commit in the proposal?',choices:[
{label:'Commit all 500 VMs in six months at fixed price',impact:{customer:1,architecture:-1,effort:-2,schedule:-3,margin:-3,acr:2,alignment:0,risk:-3},feedback:'Attractive headline, weak delivery position. Unknown dependencies and application ownership become Cognizant risk.'},
{label:'Propose paid discovery, then refuse any migration schedule',impact:{customer:-2,architecture:2,effort:1,schedule:0,margin:1,acr:-1,alignment:0,risk:3},feedback:'Protects delivery but may stall the pursuit. You can usually preserve momentum without pretending uncertainty is zero.'},
{label:'Commit assessment first, publish provisional waves and gate the final migration baseline on validated dependencies',impact:{customer:3,architecture:2,effort:2,schedule:2,margin:2,acr:1,alignment:2,risk:3},feedback:'Strong bounded commitment. Customer gets a path and Cognizant keeps an explicit validation gate before execution promises harden.'}]},
{title:'The consumption temptation',context:'Microsoft asks whether the design can target higher Azure consumption. Current performance evidence supports smaller VM sizes and only two applications have a justified PaaS modernization case.',decision:'How do you shape the architecture?',choices:[
{label:'Increase VM sizes and add PaaS services to maximize ACR',impact:{customer:-3,architecture:-2,effort:-1,schedule:-1,margin:0,acr:3,alignment:-2,risk:-2},feedback:'Higher theoretical consumption, weaker customer economics and credibility. Consumption must follow justified workload design.'},
{label:'Right-size from evidence, show base consumption plus an adoption-led expansion scenario',impact:{customer:3,architecture:3,effort:2,schedule:2,margin:1,acr:1,alignment:3,risk:3},feedback:'Defensible. It separates committed consumption from upside and gives Microsoft a credible growth path.'},
{label:'Ignore Azure consumption because it is Microsoft’s concern',impact:{customer:1,architecture:1,effort:0,schedule:0,margin:0,acr:-3,alignment:-3,risk:0},feedback:'Technically possible, commercially incomplete for a Microsoft-aligned pursuit. Senior pre-sales should understand the consumption consequence.'}]},
{title:'The discount request',context:'Procurement asks for a 15% services discount two days before submission. Current gross margin is acceptable but not generous. Scope has not changed.',decision:'What do you do?',choices:[
{label:'Give 15% to protect the win',impact:{customer:2,architecture:0,effort:0,schedule:0,margin:-3,acr:0,alignment:0,risk:-2},feedback:'Fast concession with no exchange of value. Delivery risk remains while commercial protection disappears.'},
{label:'Model the impact and trade price against scope, term, payment, staffing mix or phased options',impact:{customer:2,architecture:0,effort:2,schedule:1,margin:3,acr:0,alignment:2,risk:3},feedback:'Commercially disciplined. A discount becomes a negotiated trade rather than unexplained margin erosion.'},
{label:'Reject any discount immediately',impact:{customer:-2,architecture:0,effort:0,schedule:0,margin:3,acr:0,alignment:-1,risk:1},feedback:'Protects margin but may ignore legitimate deal levers. First understand the buying constraint and available trades.'}]},
{title:'The funding assumption',context:'A Microsoft contact says the opportunity may qualify for funding. No written approval or program confirmation exists. Sales wants to show the funding as a customer saving.',decision:'What goes into the commercial proposal?',choices:[
{label:'Deduct expected funding from the customer price',impact:{customer:2,architecture:0,effort:0,schedule:0,margin:-3,acr:1,alignment:-2,risk:-3},feedback:'This converts uncertainty into a contractual expectation. If funding fails, someone must absorb the gap.'},
{label:'Show funding as potential and conditional, with eligibility, approval and evidence requirements clearly separated from Cognizant price',impact:{customer:3,architecture:0,effort:1,schedule:1,margin:3,acr:2,alignment:3,risk:3},feedback:'Correct separation of partner services commercials from an external approval process.'},
{label:'Do not mention Microsoft funding at all',impact:{customer:0,architecture:0,effort:0,schedule:0,margin:2,acr:-1,alignment:-2,risk:2},feedback:'Safe but misses a potentially useful joint value lever. Conditional language is usually stronger than silence.'}]}
]
const names:Record<keyof Impact,string>={customer:'Customer',architecture:'Architecture',effort:'Effort',schedule:'Schedule',margin:'Margin',acr:'Azure consumption',alignment:'Microsoft alignment',risk:'Delivery protection'}
export function DealSimulator({bestScore,onScore}:{bestScore:number;onScore:(n:number)=>void}){const [answers,setAnswers]=useState<Record<number,number>>({}),[active,setActive]=useState(0);const answered=Object.keys(answers).length;const total=useMemo(()=>Object.entries(answers).reduce((sum,[si,ci])=>sum+Object.values(scenarios[+si].choices[ci]).length*0+Object.values(scenarios[+si].choices[ci].impact).reduce((a,b)=>a+b,0),0),[answers]);const max=scenarios.length*19;const score=Math.max(0,Math.min(100,Math.round((total+scenarios.length*24)/(max+scenarios.length*24)*100)));const choose=(i:number)=>{const next={...answers,[active]:i};setAnswers(next);if(Object.keys(next).length===scenarios.length){const t=Object.entries(next).reduce((sum,[si,ci])=>sum+Object.values(scenarios[+si].choices[ci].impact).reduce((a,b)=>a+b,0),0);const p=Math.max(0,Math.min(100,Math.round((t+scenarios.length*24)/(max+scenarios.length*24)*100)));onScore(p)}};const s=scenarios[active],picked=answers[active];return <section className="panel lab"><p className="eyebrow">DEAL DECISION SIMULATOR</p><h2>Every pre-sales decision moves more than one number</h2><p className="lead">Choose first. Then inspect the consequence across customer value, architecture, effort, schedule, margin, Azure consumption, Microsoft alignment and delivery protection.</p><div className="sim-score"><strong>{answered}/{scenarios.length}</strong><span>decisions made</span><strong>{answered===scenarios.length?`${score}%`:'In progress'}</strong><span>scenario signal · best {bestScore}%</span></div><div className="sim-tabs">{scenarios.map((x,i)=><button className={`${active===i?'active ':''}${answers[i]!==undefined?'done':''}`} onClick={()=>setActive(i)} key={x.title}>{i+1}. {x.title}</button>)}</div><article className="sim-case"><small>CONTEXT</small><p>{s.context}</p><h3>{s.decision}</h3><div className="sim-choices">{s.choices.map((c,i)=><button className={picked===i?'selected':''} onClick={()=>choose(i)} key={c.label}>{c.label}</button>)}</div>{picked!==undefined&&<><div className="impact-grid">{Object.entries(s.choices[picked].impact).map(([k,v])=><div key={k}><span>{names[k as keyof Impact]}</span><strong className={v>0?'positive':v<0?'negative':''}>{v>0?'+':''}{v}</strong></div>)}</div><div className="review"><strong>Consequence</strong><p>{s.choices[picked].feedback}</p></div></>}</article><p className="formula">Scoring is a learning model for this fictional Contoso case. It demonstrates trade-offs, not a universal deal formula.</p></section>}
