import {useMemo,useState} from 'react'
type Challenge={role:string,care:string,q:string,good:string[],weak:string[]}
const challenges:Challenge[]=[
{role:'Sales Leader',care:'Win strategy, differentiation, customer urgency',q:'Why should the customer buy this now, and why from us?',good:['Tie urgency to business impact and decision criteria','Differentiate with evidence, delivery model and Microsoft alignment','Name the buying decision and next action'],weak:['Lead with Azure features','Promise an aggressive date to create urgency']},
{role:'Delivery Leader',care:'Feasibility, staffing, dependencies, transition',q:'What makes the six-month commitment defensible?',good:['Separate target date from validated delivery baseline','Show dependency, wave and resource evidence','Define gates and change triggers'],weak:['Say the team will work harder','Treat VM count as the migration plan']},
{role:'Finance',care:'Cost, GP, GM, contingency, approval assumptions',q:'What happens if the customer asks for another 15% discount?',good:['Show margin sensitivity before conceding','Test scope, pyramid, duration and terms','Revalidate approval if economics cross governance thresholds'],weak:['Absorb it in contingency','Reduce architecture and testing first']},
{role:'Security',care:'Identity, network, data, compliance, operational controls',q:'What security decisions can still change scope or schedule?',good:['Name unresolved controls and owners','Connect security decisions to effort and acceptance','Keep exceptions visible in RAID and SOW'],weak:['Say Azure is secure by default','Defer all security until implementation']},
{role:'Microsoft',care:'Azure consumption, strategic fit, co-sell, funding evidence',q:'How does this pursuit create credible Azure consumption?',good:['Tie consumption to evidenced workloads and services','Separate forecast from committed consumption','Validate funding eligibility before commercial treatment'],weak:['Increase sizing to strengthen ACR','Assume funding will be approved later']}
]
export function ExecutiveDealReview(){const [answers,setAnswers]=useState<Record<number,string[]>>({}),[submitted,setSubmitted]=useState(false);const toggle=(i:number,a:string)=>setAnswers(x=>({...x,[i]:(x[i]||[]).includes(a)?(x[i]||[]).filter(v=>v!==a):[...(x[i]||[]),a]}));const score=useMemo(()=>{let earned=0,total=0;challenges.forEach((c,i)=>{total+=c.good.length+c.weak.length;(answers[i]||[]).forEach(a=>{if(c.good.includes(a))earned++;if(c.weak.includes(a))earned--})});return Math.max(0,Math.round(earned/total*200))},[answers]);return <section className="panel lab"><p className="eyebrow">EXECUTIVE DEAL REVIEW</p><h2>Defend the pursuit, not the slide deck</h2><p className="lead">You are presenting Contoso to a cross-functional review board. Choose the points you would make. The exercise rewards evidence, decision clarity and delivery protection.</p><div className="exec-story"><div><small>PROBLEM</small><strong>Legacy estate + data-center exit pressure</strong></div><i>→</i><div><small>IMPACT</small><strong>Time pressure with incomplete dependencies</strong></div><i>→</i><div><small>SOLUTION</small><strong>Evidence-led Azure migration waves</strong></div><i>→</i><div><small>ECONOMICS</small><strong>Validate scope, pyramid, margin and ACR</strong></div><i>→</i><div><small>DECISION</small><strong>Approve discovery gates before baseline commitment</strong></div></div><div className="board-grid">{challenges.map((c,i)=><article key={c.role}><small>{c.role}</small><h3>{c.q}</h3><p>{c.care}</p><div className="board-options">{[...c.good,...c.weak].map(a=><button className={(answers[i]||[]).includes(a)?'selected':''} onClick={()=>toggle(i,a)} key={a}>{a}</button>)}</div>{submitted&&<div className="board-feedback"><strong>Review lens</strong><p>Strong responses: {c.good.join('; ')}.</p><p>Avoid: {c.weak.join('; ')}.</p></div>}</article>)}</div><div className="assessment-actions"><button className="primary-action" onClick={()=>setSubmitted(true)}>Submit to review board</button><button className="ghost" onClick={()=>{setAnswers({});setSubmitted(false)}}>Reset</button></div>{submitted&&<div className="exec-result"><strong>{score}%</strong><div><h3>{score>=80?'Board-ready pattern':score>=55?'Needs sharper evidence':'High commitment risk'}</h3><p>This is a training score. In a real review, approval depends on validated pursuit evidence and the organization's governance.</p></div></div>}<div className="review"><strong>Executive communication pattern</strong><p>Problem → impact → recommendation → economics → risk → decision required. Technical depth comes second. Never hide a material assumption behind architecture detail.</p></div></section>}
