import {useState} from 'react'
const roles=[
['AE','Account Executive','Customer relationship, opportunity strategy and commercial motion','Business priority, executive sponsorship, buying process','Bring a crisp customer outcome, decision map and partner value.'],
['STU','Specialist Team Unit','Technical sales specialists aligned to solution areas','Technical fit, competitive differentiation, Azure opportunity','Align architecture and consumption story before customer workshops.'],
['CSU','Customer Success Unit','Post-sale success, adoption and consumption','Realized value, adoption blockers, workload health','Show how the proposed landing zone and operating model survive after go-live.'],
['PDM','Partner Development Manager','Strategic partner relationship and joint business','Partner capability, pipeline, co-sell and growth','Connect the pursuit to repeatable Cognizant capability, not one isolated deal.'],
['Specialist','Microsoft Solution Specialist','Deep solution-area opportunity ownership','Workload outcome, technical win, consumption','Use them to challenge assumptions and strengthen the technical win plan.'],
['Cognizant Sales','Account / Sales Lead','Owns account pursuit and customer commercial relationship','Win strategy, TCV, competition, timing','Protect the win while refusing unsupported delivery commitments.'],
['Delivery','Delivery Leadership','Owns execution feasibility and delivery outcomes','Scope clarity, staffing, schedule, dependencies','Get feasibility sign-off before proposal promises become contractual facts.'],
['Finance','Commercial / Finance','Validates economics and financial governance','Revenue, cost, margin, contingency','Make estimate assumptions traceable so margin is explainable, not accidental.']
]
const scenarios=[
{q:'Microsoft suggests potential funding, but approval is not documented. Customer asks you to reduce Cognizant price by the expected funding amount.',good:'Keep services pricing independent until funding is formally approved. State funding as conditional and validate eligibility, evidence and approval path.',bad:'Do not convert an unapproved Microsoft program into a Cognizant commercial commitment.',who:'PDM / Specialist + Cognizant Sales + Finance'},
{q:'The Microsoft specialist wants a larger Azure design to maximize consumption, while customer workload evidence supports a smaller footprint.',good:'Anchor sizing to customer evidence. Show the consumption drivers and expansion path if adoption grows.',bad:'Do not oversize merely to increase ACR. It damages trust and can create cost objections.',who:'Microsoft Specialist + Customer Architect'},
{q:'Sales wants a six-month fixed-price commitment before dependency discovery is complete.',good:'Offer a bounded commitment: discovery/assessment gate, provisional waves, explicit assumptions and change triggers.',bad:'Do not hide uncertainty inside contingency or accept a schedule you cannot defend.',who:'Cognizant Sales + Delivery + Customer Sponsor'},
{q:'Microsoft AE asks for the partner value in one minute before an executive customer call.',good:'Lead with business outcome, why Cognizant, delivery path, Azure consumption impact and the decision needed from the customer.',bad:'Do not start with a long Azure service catalogue or architecture diagram.',who:'Microsoft AE + Cognizant Sales'}
]
export function MicrosoftEcosystem(){const [selected,setSelected]=useState(0),[scenario,setScenario]=useState(0),[revealed,setRevealed]=useState(false);const r=roles[selected],s=scenarios[scenario];return <section className="panel lab"><p className="eyebrow">MICROSOFT + COGNIZANT ECOSYSTEM</p><h2>Know who owns the decision before you enter the meeting</h2><p className="lead">Use this as a stakeholder rehearsal tool. Roles vary by account and Microsoft organization, so confirm actual ownership on each pursuit.</p><div className="ecosystem-grid"><div className="role-rail">{roles.map((x,i)=><button className={selected===i?'active':''} onClick={()=>setSelected(i)} key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></button>)}</div><article className="role-detail"><small>ROLE</small><h3>{r[0]} · {r[1]}</h3><p>{r[2]}</p><div><strong>What they care about</strong><p>{r[3]}</p></div><div><strong>Your Senior Manager move</strong><p>{r[4]}</p></div></article></div><div className="scenario-box"><div className="section-heading"><div><p className="eyebrow">STAKEHOLDER SIMULATOR</p><h3>{s.q}</h3></div><span className="stage-chip">{s.who}</span></div>{revealed?<><div className="review"><strong>Recommended response</strong><p>{s.good}</p></div><div className="red-flag"><strong>Risk to avoid</strong><p>{s.bad}</p></div></>:<button className="primary-action" onClick={()=>setRevealed(true)}>Reveal Senior Manager response</button>}<div className="scenario-nav"><button className="ghost" onClick={()=>{setScenario((scenario+scenarios.length-1)%scenarios.length);setRevealed(false)}}>Previous</button><span>{scenario+1}/{scenarios.length}</span><button className="ghost" onClick={()=>{setScenario((scenario+1)%scenarios.length);setRevealed(false)}}>Next scenario</button></div></div></section>}
