type Area='home'|'learn'|'practice'|'pursuit'|'progress'
export type ProductView='command'|'learningos'|'academy'|'learn'|'ecosystem'|'meeting'|'discovery'|'architecture'|'factory'|'loading'|'microsoft'|'sowrisk'|'economics'|'labs'|'assessment'|'simulator'|'defend'|'boardroom'|'capstone'|'qualify'|'control'|'review'|'artifacts'|'skills'
const groups:{id:Area;label:string;description:string;items:{view:ProductView;label:string;hint:string}[]}[]=[
{id:'home',label:'Home',description:'Orient yourself and resume the next useful action.',items:[{view:'command',label:'Command Center',hint:'Deal journey, current stage and mission'}]},
{id:'learn',label:'Learn',description:'Build concepts before you make commitments.',items:[{view:'learningos',label:'Learning OS',hint:'Personalized daily learning queue'},{view:'academy',label:'55-Module Academy',hint:'Full pre-sales curriculum'},{view:'learn',label:'8-Week Journey',hint:'Structured ramp-up path'},{view:'ecosystem',label:'Microsoft + Cognizant',hint:'Roles, co-sell and joint motion'}]},
{id:'practice',label:'Practice',description:'Turn knowledge into repeatable judgement.',items:[{view:'meeting',label:'Meeting Simulator',hint:'Stakeholder discovery practice'},{view:'discovery',label:'Discovery Simulator',hint:'Evidence and dependency decisions'},{view:'architecture',label:'Architecture Decisions',hint:'Trade-offs, not diagram theatre'},{view:'factory',label:'Migration Factory',hint:'Wave execution and throughput'},{view:'loading',label:'Resource Loading',hint:'People, phases and utilization'},{view:'microsoft',label:'Co-Sell + ACR',hint:'Microsoft pursuit alignment'},{view:'sowrisk',label:'SOW Risk Engine',hint:'Find contractual exposure'},{view:'economics',label:'Deal Economics',hint:'Revenue, cost, margin and discount'},{view:'labs',label:'Deal Labs',hint:'Focused hands-on exercises'},{view:'assessment',label:'Assessment',hint:'Knowledge recall'},{view:'simulator',label:'Decision Simulator',hint:'Judgement under trade-offs'},{view:'defend',label:'Solution Defence',hint:'Practice defending recommendations'},{view:'boardroom',label:'Defence Boardroom',hint:'Executive pressure simulation'}]},
{id:'pursuit',label:'Pursuit',description:'Run the opportunity as an integrated Senior Manager workflow.',items:[{view:'capstone',label:'Capstone Pursuit',hint:'End-to-end consequence-driven deal'},{view:'qualify',label:'Qualification War Room',hint:'Decide whether and how to pursue'},{view:'control',label:'Pursuit Control',hint:'Track deal readiness and exposure'},{view:'review',label:'Executive Deal Review',hint:'Leadership-level decision framing'},{view:'artifacts',label:'Artifact Workbench',hint:'Build reusable pursuit outputs'}]},
{id:'progress',label:'My Progress',description:'Inspect evidence of mastery and choose what to improve next.',items:[{view:'skills',label:'Skills Radar',hint:'Readiness across core disciplines'},{view:'learningos',label:'Next Best Action',hint:'Weak-area driven learning plan'},{view:'assessment',label:'Knowledge Score',hint:'Retest weak concepts'},{view:'artifacts',label:'Artifact Evidence',hint:'Track outputs you can actually build'}]}
]
export function ProductHub({view,onNavigate}:{view:ProductView;onNavigate:(v:ProductView)=>void}){const active=groups.find(g=>g.items.some(i=>i.view===view))?.id??'home';return <><nav className="primary-nav">{groups.map(g=><button key={g.id} className={active===g.id?'active':''} onClick={()=>onNavigate(g.items[0].view)}>{g.label}</button>)}</nav><section className="context-nav"><div><strong>{groups.find(g=>g.id===active)?.label}</strong><span>{groups.find(g=>g.id===active)?.description}</span></div><div className="context-items">{groups.find(g=>g.id===active)?.items.map(i=><button key={`${active}-${i.view}-${i.label}`} className={view===i.view?'active':''} onClick={()=>onNavigate(i.view)} title={i.hint}><strong>{i.label}</strong><small>{i.hint}</small></button>)}</div></section></>}
