import {useEffect,useMemo,useState} from 'react'
type Status='Open'|'Watching'|'Closed';type Item={id:string;type:'Risk'|'Assumption'|'Decision'|'Action'|'Change';text:string;owner:string;status:Status;impact:'Low'|'Medium'|'High'}
const seed:Item[]=[
{id:'R1',type:'Risk',text:'Six-month migration target is not yet supported by validated application dependencies.',owner:'Cognizant Solution Lead',status:'Open',impact:'High'},
{id:'A1',type:'Assumption',text:'Customer application owners will be available during discovery and wave validation.',owner:'Customer PMO',status:'Watching',impact:'High'},
{id:'D1',type:'Decision',text:'Migration baseline will be gated on dependency validation rather than inventory count alone.',owner:'Joint Design Authority',status:'Closed',impact:'High'},
{id:'A2',type:'Action',text:'Validate business criticality for the remaining application portfolio.',owner:'Customer App Owners',status:'Open',impact:'High'},
{id:'A3',type:'Action',text:'Confirm Microsoft funding eligibility and evidence requirements before proposal treatment.',owner:'Microsoft / Cognizant',status:'Open',impact:'Medium'},
{id:'C1',type:'Change',text:'Any material increase in application count after baseline triggers estimate and schedule review.',owner:'Cognizant Commercial Lead',status:'Watching',impact:'Medium'}]
const store='azure-presales-pursuit-control'
export function PursuitControlRoom({artifactsCompleted,stagesCompleted}:{artifactsCompleted:number;stagesCompleted:number}){const [items,setItems]=useState<Item[]>(()=>{try{return JSON.parse(localStorage.getItem(store)||'null')||seed}catch{return seed}});const [filter,setFilter]=useState('All');useEffect(()=>localStorage.setItem(store,JSON.stringify(items)),[items]);const openHigh=items.filter(x=>x.status!=='Closed'&&x.impact==='High').length,closed=items.filter(x=>x.status==='Closed').length,actions=items.filter(x=>x.type==='Action'&&x.status!=='Closed').length;const health=useMemo(()=>Math.max(0,Math.min(100,Math.round(35+stagesCompleted/14*25+artifactsCompleted/17*25+closed/items.length*15-openHigh*7))),[stagesCompleted,artifactsCompleted,closed,items.length,openHigh]);const signal=health>=80?'Controlled':health>=60?'Watch':'At risk';const visible=filter==='All'?items:items.filter(x=>x.type===filter);const cycle=(id:string)=>setItems(xs=>xs.map(x=>x.id===id?{...x,status:x.status==='Open'?'Watching':x.status==='Watching'?'Closed':'Open'}:x));return <section className="panel lab"><p className="eyebrow">PURSUIT CONTROL ROOM</p><h2>Run the deal as one system</h2><p className="lead">Contoso pursuit health combines delivery gates with unresolved risks, assumptions, decisions, actions and scope changes. The score is a training signal, not a commercial approval.</p><div className="control-kpis"><div><strong>{health}%</strong><span>Deal health · {signal}</span></div><div><strong>{openHigh}</strong><span>Open high-impact items</span></div><div><strong>{actions}</strong><span>Outstanding actions</span></div><div><strong>{artifactsCompleted}/17</strong><span>Evidence artifacts</span></div></div><div className="gate-flow"><span>QUALIFY</span><i>→</i><span>DISCOVER</span><i>→</i><span>ASSESS</span><i>→</i><span>ARCHITECT</span><i>→</i><span>ESTIMATE</span><i>→</i><span>COMMERCIAL</span><i>→</i><span>PROPOSE</span><i>→</i><span>DEFEND</span><i>→</i><span>HANDOVER</span></div><div className="control-toolbar">{['All','Risk','Assumption','Decision','Action','Change'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="control-table"><div className="control-row head"><span>Type</span><span>Issue / decision</span><span>Owner</span><span>Impact</span><span>Status</span></div>{visible.map(x=><div className="control-row" key={x.id}><strong>{x.type}</strong><span>{x.text}</span><span>{x.owner}</span><span className={x.impact==='High'?'high':''}>{x.impact}</span><button onClick={()=>cycle(x.id)}>{x.status}</button></div>)}</div><div className="review"><strong>Senior Manager operating rule</strong><p>Do not hide uncertainty inside the architecture or estimate. Give it an owner, validation action, decision date and commercial consequence. Escalate when an unresolved item can change scope, schedule, price, margin, security or contractual exposure.</p></div></section>}
