const templates=[
{type:'Excel',title:'Resource Loading Model',file:'Azure_Resource_Loading_Template.xlsx',desc:'Phase-based FTE, hours, delivery cost, revenue, gross profit and margin model.',checks:['Phase demand','Onshore/offshore mix','Testing + governance','Contingency + stabilization']},
{type:'Excel',title:'SOW Builder',file:'Azure_SOW_Builder_Template.xlsx',desc:'Structured SOW checklist covering scope, deliverables, assumptions, exclusions, acceptance and change control.',checks:['Scope baseline','Customer responsibilities','Acceptance criteria','Change triggers']},
{type:'Excel',title:'RFP Response Matrix',file:'Azure_RFP_Response_Template.xlsx',desc:'Requirement-by-requirement response, compliance, evidence, ownership, review status and risk tracker.',checks:['Compliance','Evidence','Assumptions','Reviewer approval']},
{type:'Excel',title:'RFI Response Matrix',file:'Azure_RFI_Response_Template.xlsx',desc:'Early-stage response matrix for capability, architecture, migration, security, commercial and Microsoft questions.',checks:['Clarifications','Evidence','Ownership','Open risk']},
{type:'Excel',title:'Discovery Questionnaire',file:'Azure_Discovery_Questionnaire.xlsx',desc:'Workshop question bank spanning business, estate, apps, data, network, identity, security, operations and commercials.',checks:['Answer evidence','Confidence','Estimate impact','Decision owner']},
{type:'PowerPoint',title:'Solution Presentation',file:'Azure_Solution_Presentation_Template.pptx',desc:'Executive-ready storyline from customer problem and discovery evidence through architecture, migration, security, plan and decisions.',checks:['Executive summary','Architecture visual','Migration approach','Risks + decisions']},
{type:'PowerPoint',title:'Solution Defence Boardroom',file:'Azure_Solution_Defence_Template.pptx',desc:'Defence deck for executive, architecture, timeline, commercial and security challenges with evidence-led response framing.',checks:['Problem → evidence','Trade-offs','Commercial defence','Objection log']}
]
const base='https://github.com/myroad2cloud/azure-presales-command-center/raw/main/public/templates/'
export function TemplateCenter(){return <section className="panel lab"><p className="eyebrow">DOWNLOADABLE PRE-SALES TOOLKIT</p><h2>Templates you can take into a real pursuit</h2><p className="lead">Use these as working accelerators, not as Cognizant-approved legal, pricing or contractual artifacts. Replace illustrative data with validated customer and internal information, and route contractual/commercial content through the required approval process.</p><div className="template-grid">{templates.map(t=><article key={t.file}><div className="template-head"><span>{t.type}</span><h3>{t.title}</h3></div><p>{t.desc}</p><div className="template-checks">{t.checks.map(x=><small key={x}>{x}</small>)}</div><a href={base+t.file} download>Download {t.type==='Excel'?'.xlsx':'.pptx'} template</a></article>)}</div><div className="review"><strong>Senior Manager template rule</strong><p>A polished template is not evidence. Keep facts, assumptions and unresolved decisions visibly separate. Protect delivery feasibility before scope, timeline or commercials become commitments.</p></div></section>}
