import {useState} from 'react'
import {downloadExcelTemplate,downloadPptTemplate} from '../utils/templateGenerators'
const templates=[
{key:'resource',type:'Excel',title:'Resource Loading Model',desc:'Phase-based FTE, hours, delivery cost, revenue, gross profit and margin model.',checks:['Phase demand','Onshore/offshore mix','Testing + governance','Contingency + stabilization']},
{key:'sow',type:'Excel',title:'SOW Builder',desc:'Structured SOW checklist covering scope, deliverables, assumptions, exclusions, acceptance and change control.',checks:['Scope baseline','Customer responsibilities','Acceptance criteria','Change triggers']},
{key:'rfp',type:'Excel',title:'RFP Response Matrix',desc:'Requirement-by-requirement response, compliance, evidence, ownership, review status and risk tracker.',checks:['Compliance','Evidence','Assumptions','Reviewer approval']},
{key:'rfi',type:'Excel',title:'RFI Response Matrix',desc:'Early-stage response matrix for capability, architecture, migration, security, commercial and Microsoft questions.',checks:['Clarifications','Evidence','Ownership','Open risk']},
{key:'questionnaire',type:'Excel',title:'Discovery Questionnaire',desc:'Workshop question bank spanning business, estate, apps, data, network, identity, security, operations and commercials.',checks:['Answer evidence','Confidence','Estimate impact','Decision owner']},
{key:'solution',type:'PowerPoint',title:'Solution Presentation',desc:'Executive-ready storyline from customer problem and discovery evidence through architecture, migration, security, plan and decisions.',checks:['Executive summary','Architecture visual','Migration approach','Risks + decisions']},
{key:'defence',type:'PowerPoint',title:'Solution Defence Boardroom',desc:'Defence deck for executive, architecture, timeline, commercial and security challenges with evidence-led response framing.',checks:['Problem → evidence','Trade-offs','Commercial defence','Objection log']}
]
export function TemplateCenter(){const [busy,setBusy]=useState('');const get=async(t:(typeof templates)[number])=>{setBusy(t.key);try{if(t.type==='Excel')downloadExcelTemplate(t.key);else await downloadPptTemplate(t.key as 'solution'|'defence')}finally{setBusy('')}};return <section className="panel lab"><p className="eyebrow">DOWNLOADABLE PRE-SALES TOOLKIT</p><h2>Templates you can take into a real pursuit</h2><p className="lead">The files are generated directly in your browser. Use them as working accelerators, not as Cognizant-approved legal, pricing or contractual artifacts. Replace illustrative data with validated customer and internal information and follow required approvals.</p><div className="template-grid">{templates.map(t=><article key={t.key}><div className="template-head"><span>{t.type}</span><h3>{t.title}</h3></div><p>{t.desc}</p><div className="template-checks">{t.checks.map(x=><small key={x}>{x}</small>)}</div><button onClick={()=>get(t)} disabled={busy===t.key}>{busy===t.key?'Building file…':`Download ${t.type==='Excel'?'.xlsx':'.pptx'} template`}</button></article>)}</div><div className="review"><strong>Senior Manager template rule</strong><p>A polished template is not evidence. Keep facts, assumptions and unresolved decisions visibly separate. Protect delivery feasibility before scope, timeline or commercials become commitments.</p></div></section>}
